kind: Service
apiVersion: v1
metadata:
  name: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 32760
    nodePort: 32760

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
      track: stable
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: train-schedule
        image: ashish158/practice:$BUILD_NUMBER
        ports:
        - containerPort: 32760
